[package]
name = "pkgdeck"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
pkgdeck-core.workspace = true
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true
cxx-gen.workspace = true

[lints]
workspace = true

[dev-dependencies.pkgdeck-tools]
path = "../pkgdeck-tools"
