[package]
name = "pkd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
signal-hook.workspace = true
serde.workspace = true
serde_json.workspace = true
pkgdeck-core.workspace = true
clap.workspace = true
unicode-width.workspace = true
rustix = { workspace = true, features = ["termios"] }

[lints]
workspace = true
